export const BUNDLES_SCREEN_COPY = {
  redirecting: "Redirecting…",
  loadingLabel: "Loading bundles",
  errorTitle: "Could not load bundles",
  errorFallback: "Something went wrong while loading bundle information.",
  pageTitle: "Bundles",
  assetHubAction: "Asset Hub",
  schedulerTitle: "Delivery schedule",
  schedulerSummaryEveryPrefix: "Every ",
  schedulerSummarySeparator: " · ",
  schedulerNoSchedulerTitle: "No delivery schedule linked",
  schedulerNoSchedulerBody:
    "This account does not have a scheduler configured yet. Bundle delivery settings may still be managed in organisation settings.",
  schedulerDeliveryDayUnknown: "Not set",
  schedulerNextDeliveryToday: "Today",
  schedulerNextDeliveryInOneDay: "In 1 day",
  schedulerNextDeliveryInDaysPrefix: "In ",
  schedulerNextDeliveryInDaysSuffix: " days",
  schedulerRunStatusLabel: "Run status",
  schedulerChangeDeliveryDayAction: "Change delivery day",
  schedulerUpdatedLabel: "Schedule updated",
  schedulerUpdatedShort: "Updated",
  renderListPlaceholderTitle: "Render history",
  renderListPlaceholderBody: "Render history and delivery links will appear here.",
  detailLoadingLabel: "Loading render",
  detailErrorTitle: "Could not load render",
  detailPlaceholderTitle: "Render detail",
  detailPlaceholderBody: "Render detail and external asset links — coming soon.",
  detailBackAction: "Back to bundles",
  invalidRenderId: "The render id in the URL is not valid.",
  renderNotFound: "This render was not found or may have been removed.",
  feedbackErrorLabel: "Error",
  feedbackInfoLabel: "Info",
  feedbackWarningLabel: "Warning",
  feedbackRetryAction: "Retry",
} as const;
