import {
  Check,
  X,
  Plus,
  Minus,
  Search,
  Home,
  User,
  Settings,
  Mail,
  Phone,
  Calendar,
  Clock,
  Star,
  Heart,
  Eye,
  EyeOff,
  Download,
  Upload,
  Edit,
  Trash,
  Copy,
  Share,
  Link,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Menu,
  Filter,
  RotateCcw,
  RotateCw,
  Loader2,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Repeat1,
  Mic,
  MicOff,
  Video,
  VideoOff,
  Camera,
  Image,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  Folder,
  FolderOpen,
  Database,
  Server,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Sun,
  Moon,
  Zap,
  Flame,
  Droplets,
  Wind,
  Thermometer,
  Umbrella,
  Shield,
  Lock,
  Unlock,
  Key,
  Bell,
  BellOff,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,
  MinusCircle,
  PlusCircle,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Activity,
  BarChart,
  BarChart3,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  CreditCard,
  Wallet,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Tag,
  Percent,
  Hash,
  AtSign,
} from "lucide-react";

// Create the Icon namespace for easy access
// This pattern allows you to change the underlying icon without updating component calls
// Example: Change Check: Check to Check: CheckCircle to use a different icon
// Your component calls stay the same: <Icon.Check />
export const Icon = {
  Check: Check, // Try changing this to Check: CheckCircle to see the difference
  X: X,
  Plus: Plus,
  Minus: Minus,
  Search: Search,
  Home: Home,
  User: User,
  Settings: Settings,
  Mail: Mail,
  Phone: Phone,
  Calendar: Calendar,
  Clock: Clock,
  Star: Star,
  Heart: Heart,
  Eye: Eye,
  EyeOff: EyeOff,
  Download: Download,
  Upload: Upload,
  Edit: Edit,
  Trash: Trash,
  Copy: Copy,
  Share: Share,
  Link: Link,
  ExternalLink: ExternalLink,
  ArrowRight: ArrowRight,
  ArrowLeft: ArrowLeft,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  Menu: Menu,
  Filter: Filter,
  RotateCcw: RotateCcw,
  RotateCw: RotateCw,
  Loader2: Loader2,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
  Maximize: Maximize,
  Minimize: Minimize,
  Volume: Volume,
  VolumeX: VolumeX,
  Volume1: Volume1,
  Volume2: Volume2,
  Play: Play,
  Pause: Pause,
  SkipBack: SkipBack,
  SkipForward: SkipForward,
  Rewind: Rewind,
  FastForward: FastForward,
  Shuffle: Shuffle,
  Repeat: Repeat,
  Repeat1: Repeat1,
  Mic: Mic,
  MicOff: MicOff,
  Video: Video,
  VideoOff: VideoOff,
  Camera: Camera,
  Image: Image,
  File: File,
  FileText: FileText,
  FileImage: FileImage,
  FileVideo: FileVideo,
  FileAudio: FileAudio,
  Folder: Folder,
  FolderOpen: FolderOpen,
  Database: Database,
  Server: Server,
  Cloud: Cloud,
  CloudRain: CloudRain,
  CloudSnow: CloudSnow,
  CloudLightning: CloudLightning,
  Sun: Sun,
  Moon: Moon,
  Zap: Zap,
  Flame: Flame,
  Droplets: Droplets,
  Wind: Wind,
  Thermometer: Thermometer,
  Umbrella: Umbrella,
  Shield: Shield,
  Lock: Lock,
  Unlock: Unlock,
  Key: Key,
  Bell: Bell,
  BellOff: BellOff,
  AlertCircle: AlertCircle,
  AlertTriangle: AlertTriangle,
  Info: Info,
  HelpCircle: HelpCircle,
  CheckCircle: CheckCircle,
  XCircle: XCircle,
  MinusCircle: MinusCircle,
  PlusCircle: PlusCircle,
  Circle: Circle,
  Square: Square,
  Triangle: Triangle,
  Hexagon: Hexagon,
  Octagon: Octagon,
  Activity: Activity,
  BarChart: BarChart,
  BarChart3: BarChart3,
  LineChart: LineChart,
  PieChart: PieChart,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  DollarSign: DollarSign,
  CreditCard: CreditCard,
  Wallet: Wallet,
  ShoppingCart: ShoppingCart,
  ShoppingBag: ShoppingBag,
  Gift: Gift,
  Tag: Tag,
  Percent: Percent,
  Hash: Hash,
  AtSign: AtSign,
} as const;

// Export individual icons for direct imports
export {
  Check,
  X,
  Plus,
  Minus,
  Search,
  Home,
  User,
  Settings,
  Mail,
  Phone,
  Calendar,
  Clock,
  Star,
  Heart,
  Eye,
  EyeOff,
  Download,
  Upload,
  Edit,
  Trash,
  Copy,
  Share,
  Link,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Menu,
  Filter,
  RotateCcw,
  RotateCw,
  Loader2,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Repeat1,
  Mic,
  MicOff,
  Video,
  VideoOff,
  Camera,
  Image,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  Folder,
  FolderOpen,
  Database,
  Server,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Sun,
  Moon,
  Zap,
  Flame,
  Droplets,
  Wind,
  Thermometer,
  Umbrella,
  Shield,
  Lock,
  Unlock,
  Key,
  Bell,
  BellOff,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,
  MinusCircle,
  PlusCircle,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Activity,
  BarChart,
  BarChart3,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  CreditCard,
  Wallet,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Tag,
  Percent,
  Hash,
  AtSign,
};

// Export the main Icon namespace
export default Icon;
